os: linux
language: c
env:
  global:
    - MAKEFLAGS="-j3 --output-sync"
script:
  - rake ci
addons:
  apt:
    packages:
      - avr-libc
      - binutils-arm-none-eabi
      - binutils-avr
      - dfu-programmer
      - dfu-util
      - gcc-avr
      - gcc-arm-none-eabi
      - libnewlib-arm-none-eabi
